import os
import shutil
import requests

baseURL = os.environ.get('BASE_URL', 'https://aadarsh-ram.github.io/delta-hack-23/')
username = os.environ.get('GITHUB_USERNAME', 'aadarsh-ram')
repo = os.environ.get('GITHUB_REPO', 'delta-hack-23')
TEMPLATE = f"""
<!DOCTYPE html>
<html>
<head>
    <base href="{baseURL}">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="referrer" content="no-referrer" />
    <meta name="referrer" content="unsafe-url" />
    <meta name="referrer" content="origin" />
    <meta name="referrer" content="no-referrer-when-downgrade" />
    <meta name="referrer" content="origin-when-cross-origin" />
    <title>Versions</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    """ + """
    <style>
        body {
            font-family: Helvetica,Arial,sans-serif;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }
        code, pre {
            font-family: monospace;
        }
        .container {
            margin-top: 20px;
            margin-bottom: 20px;
        }
        footer {
            background-color: #f5f5f5;
            color: black;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="container">
<h1>Versions</h1>
{{content}}
</div>
<footer>
    <h4> Automatically generated by Docbro | Made with 💛 by Aadarsh A</h4>
</footer>
</body>
</html>
"""

api_url = f"https://api.github.com/repos/{username}/{repo}/git/trees/gh-pages"
response = requests.get(api_url)
if response.status_code == 200:
    data = response.json()
    tree = data.get('tree')
    links = []
    if tree:
        for item in sorted(tree, key=lambda x: x.get('path'), reverse=True):
            if item.get('type') == 'tree':
                path = item.get('path')
                links.append(f"""<li><a href="{path}/index.html">Version {path}</a></li>""")
    
    content = '\n'.join(links)
    html = TEMPLATE.replace('{{content}}', content)

    if os.path.exists('top-level'):
        shutil.rmtree('top-level')
    os.makedirs('top-level')

    with open("./top-level/index.html", 'w') as f:
        f.write(html)